# Generated by Django 4.1.7 on 2023-03-31 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bimestref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.CharField(max_length=25, verbose_name='Bimestre')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadoria', models.CharField(max_length=50, verbose_name='Coordenadoria')),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(max_length=100, verbose_name='Escola')),
                ('coordenadoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coordenadoria')),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdicao', models.CharField(max_length=20, verbose_name='Jurisdição')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=25, verbose_name='Componente Curricular')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bimestref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bimestref')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Professor')),
                ('coordenadoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coordenadoria')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.escola')),
                ('jurisdicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jurisdicao', verbose_name='Jurisdição')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materia', verbose_name='Componente Curricular')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20, verbose_name='Série/Ano')),
            ],
        ),
        migrations.CreateModel(
            name='Serief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20, verbose_name='Série/Ano')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=20, verbose_name='Turno')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=20, verbose_name='Turma')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.serie')),
            ],
        ),
        migrations.AddField(
            model_name='serie',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turno'),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.BooleanField()),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pergunta')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.serie', verbose_name='Série | Ano'),
        ),
        migrations.AddField(
            model_name='professor',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
        migrations.AddField(
            model_name='professor',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turno'),
        ),
        migrations.CreateModel(
            name='Materiaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=25, verbose_name='Componente Curricular')),
                ('serief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.serief')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.serie'),
        ),
        migrations.AddField(
            model_name='coordenadoria',
            name='jurisdicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jurisdicao'),
        ),
        migrations.AddField(
            model_name='bimestref',
            name='materiaf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materiaf'),
        ),
        migrations.CreateModel(
            name='Bimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.CharField(max_length=25, verbose_name='Bimestre')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materia')),
            ],
        ),
    ]
